name: Update JSON API

on:
  workflow_dispatch:
    inputs:
      force:
        description: "Force download (ignore existing files)"
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "0 * * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Pull latest changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull origin main
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Generate new data
        id: update-data
        run: npm install && npm run ${{ github.event.inputs.force == 'true' && 'update-data-force' || 'update-data' }}
      - name: Skip if no updates needed
        if: steps.update-data.outcome != 'success'
        run: |
          echo "No updates needed - manifest already up to date"
          echo "skipped=true" >> $GITHUB_OUTPUT
          exit 0
      - name: Read manifestIdUpdate.txt
        id: manifestId
        uses: juliangruber/read-file-action@v1
        with:
          path: ./manifestIdUpdate.txt
      - name: Commit & push changes
        if: steps.update-data.outcome == 'success'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[bot::update] manifest ${{ steps.manifestId.outputs.content }}"
      - name: Set job status
        if: always()
        run: |
          if [ "${{ steps.update-data.outcome }}" != "success" ]; then
            echo "::notice::Workflow skipped - no updates needed"
            echo "Job status: SKIPPED (no updates available)"
          else
            echo "::notice::Workflow completed successfully"
            echo "Job status: SUCCESS (updates applied)"
          fi
